const { executeDbQuery, supabase } = require('../shared/db');
const googleCalendar = require('../integrations/google-calendar.service');

class SchoolService {
    /**
     * Parse and log a school event, natively triggering generative automations 
     * based on the event type (e.g. generating a spouse reminder for PTMs).
     */
    async logEvent(userId, childName, eventType, title, dateStr) {
        if (!supabase) return { success: false, message: 'DB not connected' };

        // 1. Child Verification Constraint
        if (!childName) {
            return {
                success: false,
                message: `I caught that this is a school event, but which child is this for? (e.g. "Aarav's math exam" or "Myra's PTM").`
            };
        }

        const childrenOpt = await executeDbQuery(
            supabase.from('children')
                .select('*')
                .eq('user_id', userId)
                .ilike('name', `%${childName}%`)
                .limit(1)
        );

        if (!childrenOpt || childrenOpt.length === 0) {
            return { 
                success: false, 
                message: `I couldn't find a child named "${childName}" in your family database. Please clarify their exact name.` 
            };
        }

        const child = childrenOpt[0];
        const eventDate = dateStr ? new Date(dateStr) : new Date();
        const cleanDateStr = eventDate.toISOString().split('T')[0];

        // 2. Log Core School Event
        const eventRes = await executeDbQuery(
            supabase.from('school_events').insert({
                user_id: userId,
                child_id: child.id,
                title: title || `${child.name}'s ${eventType}`,
                type: eventType || 'other',
                event_date: cleanDateStr
            }).select().single()
        );

        let autoGeneratedMessage = '';

        // 3. Generative Automations (Heuristics Engine)
        if (eventType === 'ptm') {
            // Auto-Delegate to Spouse
            const dueForReminder = new Date(eventDate);
            dueForReminder.setDate(dueForReminder.getDate() - 2); // Remind 2 days before
            
            // Safeguard: If the PTM is literally tomorrow, 2 days before is yesterday! 
            // We must schedule it for RIGHT NOW.
            if (dueForReminder < new Date()) {
                dueForReminder.setTime(new Date().getTime());
            }

            await executeDbQuery(
                supabase.from('tasks').insert({
                    user_id: userId,
                    title: `Remind spouse about ${child.name}'s PTM (${title})`,
                    type: 'simple',
                    priority: 'high',
                    due_date: dueForReminder.toISOString(),
                    source_channel: 'system_automation'
                })
            );
            autoGeneratedMessage = `\n\n💡 _Automation Activity_: I've created a proactive checklist task for you to alert your spouse 2 days before the PTM.`;

        } else if (eventType === 'exam') {
            // Study Schedule Prep Automation
            const dueForPrep = new Date(eventDate);
            dueForPrep.setDate(dueForPrep.getDate() - 7); // Exactly 7 days before exam

            // Safeguard: If the Exam is 3 days away, 7 days before is in the past! Schedule for RIGHT NOW.
            if (dueForPrep < new Date()) {
                dueForPrep.setTime(new Date().getTime());
            }

            await executeDbQuery(
                supabase.from('tasks').insert({
                    user_id: userId,
                    title: `Study Schedule Prep for ${child.name}'s Exam: ${title}`,
                    type: 'simple',
                    priority: 'high',
                    due_date: dueForPrep.toISOString(),
                    source_channel: 'system_automation'
                })
            );
            autoGeneratedMessage = `\n\n💡 _Automation Activity_: I've scheduled a high-priority "Study Schedule Prep" task 7 days before the exam effectively.`;
        }

        let humanFriendlyType = eventType.toUpperCase();
        if (eventType === 'fee') humanFriendlyType = 'School Fee Reminder';

        let finalMessage = `Noted. I've officially logged the ${humanFriendlyType} for ${child.name} on ${cleanDateStr}.${autoGeneratedMessage}`;
        let responseOptions = {};

        // 4. Calendar Sync
        const gcalResponse = await googleCalendar.createEvent(userId, {
             title: `${child.name}'s ${humanFriendlyType}: ${title}`,
             description: `Ajrvis School Event Tracking`,
             due_date: eventDate.toISOString()
        });

        if (gcalResponse && gcalResponse.success) {
            finalMessage += `\n\n📅 _Event added to your Google Calendar._`;
        } else if (gcalResponse && gcalResponse.reason === 'not_connected') {
            finalMessage += `\n\n_Tip: I can automatically add this to your Google Calendar. Link your account below:_`;
            const redirectUrl = process.env.GOOGLE_REDIRECT_URL;
            if (redirectUrl) {
                responseOptions = {
                    reply_markup: {
                        inline_keyboard: [
                            [{ text: '🔗 Connect Google Calendar', url: `${redirectUrl.replace('/callback', '')}?user_id=${userId}` }]
                        ]
                    }
                };
            }
        }

        return { 
            success: true, 
            message: finalMessage,
            options: responseOptions
        };
    }

    /**
     * Flexible wrapper for the Orchestrator to track school events
     */
    async trackSchoolEvent(userId, eventData) {
        // Find child name from title if possible, or use a default
        // For "Kynaa PTM", child name is Kynaa
        let childName = null;
        if (eventData.title) {
            const match = eventData.title.match(/([A-Z][a-z]+)/); // Simple heuristic for name
            if (match) childName = match[1];
        }

        return this.logEvent(
            userId, 
            childName || 'Child', 
            eventData.type || 'other', 
            eventData.title, 
            eventData.date
        );
    }
}

module.exports = new SchoolService();
